name: Publish Extension Online

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  build:
    name: Build the extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run build-zip
    - name: Store the build output for publishing
      uses: actions/upload-artifact@v2
      with:
        path: |
          out/
          extension.zip
  publish_chrome:
    needs: build
    name: Publish to Chrome Web Store
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - uses: mnao305/chrome-extension-upload@2.2.0
      with:
        file-path: extension.zip
        extension-id: elloafhmffcedcmbdepancjijjccmail
        client-id: ${{ secrets.CLIENT_ID }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
  publish_firefox:
    needs: build
    name: Publish to Firefox Add-ons
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - uses: actions/setup-node@v2
    - run: sudo npm install -g web-ext
    - run: web-ext sign
      working-directory: out
      env:
        # WEB_EXT_ID: {c23c69a7-f889-447c-9d6b-7694be8035bc}
        WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
        WEB_EXT_TIMEOUT: 90000
        WEB_EXT_CHANNEL: listed
